# Generated by Django 5.0 on 2023-12-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_remove_item_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://cdn3.iconfinder.com/data/icons/food-delivery-60/24/order_process_loading_food_menu_nonstop_service-512.png', max_length=500),
        ),
    ]
